"""Markdown and HTML report generation for a :class:`BacktestResult`."""

from __future__ import annotations

from pathlib import Path

import plotly.graph_objects as go

from dcatoolbox.backtesting.result import BacktestResult
from dcatoolbox.config.enums import ReportFormat
from dcatoolbox.reports.text import auto_conclusion, key_findings, metrics_table
from dcatoolbox.visualization.charts import build_dashboard

__all__ = ["ReportGenerator"]

_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{title}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem auto;
         max-width: 1100px; color: #1a1a1a; line-height: 1.5; }}
 h1 {{ border-bottom: 3px solid #2563eb; padding-bottom: .3rem; }}
 h2 {{ color: #2563eb; margin-top: 2rem; }}
 table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
 th, td {{ border: 1px solid #ddd; padding: .5rem .75rem; text-align: right; }}
 th {{ background: #f1f5f9; }} td:first-child, th:first-child {{ text-align: left; }}
 .chart {{ margin: 1.5rem 0; }} .meta {{ color: #555; }}
 .footer {{ margin-top: 3rem; color: #888; font-size: .85rem; }}
</style></head><body>
<h1>{title}</h1>
<p class="meta">{period}</p>
<h2>Summary</h2><ul>{findings}</ul>
<h2>Metrics</h2>{metrics}
<h2>Charts</h2>{charts}
<h2>Conclusion</h2><p>{conclusion}</p>
<p class="footer">Generated by DCAToolBox. Past performance does not guarantee future results.</p>
</body></html>"""


class ReportGenerator:
    """Render a backtest result to Markdown, HTML or PDF."""

    def __init__(self, result: BacktestResult, figures: dict[str, go.Figure] | None = None) -> None:
        """Bind to a result and optionally reuse pre-built figures."""
        self.result = result
        self.figures = figures if figures is not None else build_dashboard(result)

    def _title(self) -> str:
        return f"DCA Backtest Report: {self.result.strategy.name} on {self.result.primary_ticker}"

    def _period(self) -> str:
        data = self.result.config.data
        return f"Period {data.start} to {data.end} | provider: {data.provider.value}"

    def to_markdown(self) -> str:
        """Return the report as a Markdown string."""
        findings = "\n".join(f"- {item}" for item in key_findings(self.result))
        table = metrics_table(self.result).to_markdown()
        return (
            f"# {self._title()}\n\n_{self._period()}_\n\n"
            f"## Summary\n\n{findings}\n\n"
            f"## Metrics\n\n{table}\n\n"
            f"## Conclusion\n\n{auto_conclusion(self.result)}\n"
        )

    def to_html(self) -> str:
        """Return the report as a self-contained HTML string."""
        charts = []
        for index, (_, figure) in enumerate(self.figures.items()):
            include = "cdn" if index == 0 else False
            inner = figure.to_html(full_html=False, include_plotlyjs=include)
            charts.append(f'<div class="chart">{inner}</div>')
        findings = "".join(f"<li>{item}</li>" for item in key_findings(self.result))
        return _HTML_TEMPLATE.format(
            title=self._title(),
            period=self._period(),
            findings=findings,
            metrics=metrics_table(self.result).to_html(border=0),
            charts="".join(charts),
            conclusion=auto_conclusion(self.result),
        )

    def generate(self, fmt: ReportFormat | str, path: Path | str) -> Path:
        """Write the report in ``fmt`` to ``path`` and return the path."""
        fmt = ReportFormat(fmt)
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        if fmt is ReportFormat.MARKDOWN:
            path.write_text(self.to_markdown(), encoding="utf-8")
        elif fmt is ReportFormat.HTML:
            path.write_text(self.to_html(), encoding="utf-8")
        else:
            from dcatoolbox.reports.pdf import write_pdf

            write_pdf(self.result, path)
        return path
